### ISSUE TITLE
Can't install vibrant deck plugin in Steam deck

### ISSUE THREAD

**Issue by ChenJunsen** [libvibrant/vibrantDeck#15]
since the Steam Deck upgrades to steam os 3.3.3。the decky loader can not install the plugin.If you install it from the plugin store,you still cant find it on steam deck

**Comment by Scrumplex** [comment]
I just checked on my Deck and it seems to work fine for me

**Comment by ChenJunsen** [comment]
what's your steam os version,3.3.3?It's wired。I can install some other plugin,but when I clicked the install button,after install loading finished,the decky loader menu has no options about vibrant deck

**Comment by Scrumplex** [comment]
I recently updated the plugin and the testers were able to run the plugin on the latest stable as well as the latest beta SteamOS. See here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/161

**Comment by ChenJunsen** [comment]
3ks,I solve it.It needs to install the pre-release version of decky loader
