### ISSUE TITLE
Per-Game settings

### ISSUE THREAD

**Issue by aizakow** [libvibrant/vibrantDeck#2]
It would be cool if it was possible to whitelist certain games. Emulators in particular I've noticed don't always look great with the saturation turned up. It also would make it more practical to continue to use the Deck-specific reshade config for some games

**Comment by Scrumplex** [comment]
I expected this feature request :D

I wasn't able to find a good way to see what game is currently *active*. The plugin is currently able to see what games are running at the moment, but it looks like the Steam UI doesn't expose which of those running games is the active one.

**Comment by Scrumplex** [comment]
An initial implementation iw available with commit 7763c3a0283fefa05c2e70df6500353fe81ed099.
Might need some more testing though.
It also doesn't carry over old settings, but that shouldn't really be a huge problem

**Comment by aizakow** [comment]
Does this commit get propagated to the decky loader frontend, or do I need to build it myself? Sorry if that's a stupid question, I only understand enough Linux to be dangerous

**Comment by Scrumplex** [comment]
> Does this commit get propagated to the decky loader frontend, or do I need to build it myself? Sorry if that's a stupid question, I only understand enough Linux to be dangerous

I would want to test this a bit further before pushing a release to decky's store.

You would need to build it yourself. IMO that's not really straightforward if you don't do plugin development yourself. I might look into providing a prebuilt zip file, that you can download and install using decky's install from URL feature

**Comment by Scrumplex** [comment]
Once https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/36 is merged, you will be able to update to 1.1.0 using Decky.

**Comment by aizakow** [comment]
Sounds good. I don't think I'll mess with building myself and will just wait. Thanks!
