### ISSUE TITLE
vibrantDeck doesn't load anymore

### ISSUE THREAD

**Issue by Logge1002** [libvibrant/vibrantDeck#21]
Currently vibrant deck won’t start in the decky plug-in please fix it

**Comment by Asti1991** [comment]
Workaround for the bug with the latest Steam Beta: went back to version 1.2.1, that fixed the error, that vibrantdeck wasn‘t able to load.

**Comment by TaroPsyche** [comment]
Can confirm with latest SD OS 3.4.4 with Decky v2.5.4-pre1
![16767891066812412638368331258849](https://user-images.githubusercontent.com/5779907/219933318-a6fd83d7-2ea7-4c1b-a8da-b8f89abc0950.jpg)

**Comment by howardhuang-ia** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/issues/374#issuecomment-1435681462

**Comment by Scrumplex** [comment]
I am going to look into this soon!

**Comment by Scrumplex** [comment]
I have submitted a bugfix release to the decky-loader plugin repo. I will close this issue, once that is merged.

**Comment by Scrumplex** [comment]
An update should be available
