### ISSUE TITLE
Consistently Causes Issues with Other Decky Plugins

### ISSUE THREAD

**Issue by TheCyberQuake** [libvibrant/vibrantDeck#3]
I've been messing with plugins and have been able to consistently recreate these issues on my steam deck:
1. Once vibrantDeck is installed, it seems to lock out downloading/installing other plugins
2. After being installed, other plugins also start being unable to read/write their own files, causing CSS Loader to be unable to find installed themes, unable to view new themes, along with PowerTools being unable to change settings.
3. All problems usually go away after removing just vibrantDeck, but sometimes also requires removing all other plugins and re-adding them

I'm not sure why vibrantDeck seems to interact with other plugins in this manner, only thing I can think of is it possibly somehow breaking folder/file access permissions.

**Comment by TheCyberQuake** [comment]
Well I'm not sure if it was something on my side that messed it up, I wouldn't think so given I've uninstalled/reinstalled about a dozen times, but I found that the permissions on the vibrantDeck folder were set slightly different to what I observed on the others. I went ahead and set it similar to the others and they all seem to be playing along now. So unsure if it's a weird bug with vibrantLinux, Decky Loader, or something somehow borked on my side

**Comment by Scrumplex** [comment]
I think I had a similar issue once. Not sure if it is consistent though.

Can you post the permissions it had before you fixed it manually?

**Comment by TrainDoctor** [comment]
I was encountering this issue but after I approved the update to 1.0.1 for vibrant deck I wasn't able to re-create the issue you described @TheCyberQuake. Go ahead and install 1.0.1 and see if that helps.

**Comment by TheCyberQuake** [comment]
Still getting the same issue again after updating. It seems the only way I've been able to consistently get it playing nice is to remove all plugins, install vibrantDeck, backup the folder somewhere else, uninstall vibrantDeck, install the other plugins, reboot to get them to fully kick in, then move the folder I backed up back to the right spot (temporarily changing permissions from Owner can only read to owner can read/write to get the file moved, changing back to 555 afterward). Once I install vibrantDeck, no other plugins like to download/install afterwards, and once I install the other plugins I use (Fantastic, System Toolbox, CSS Loader, PowerTools, DeckFAQs). Sometimes I can get other plugins to install after, but they end up broken, like CSS Loader being unable to view any themes both installed and from the downloader, PowerTools no longer will change any settings, etc.

**Comment by joamjoamjoam** [comment]
Had an issue while developing my plugin also where the permission are reset in the homebrew/plugins directory to remove write access whenever my deck is rebooted. I just assumed it was normal behavior but maybe not.

**Comment by TheCyberQuake** [comment]
The rest of the plugins seems to typically have their folders set to 555 (read only for all parties including owner), and having them set that way seems to work fine. I'm not sure what the intended permission is _supposed_ to be, but that's what the rest were sitting at and having them set that way along with vibrantDeck (after temp-changing those permissions to do copy the folder over from a local backup) everything seems to work as intended. 
I have found though that after enough times of setting the plugins folder as RWX for owner and uninstalling all plugins, Literally in the same session of doing the same stuff multiple times to try to start further pinpointing the issue, things started to just work, even though I haven't done anything different from the last time. I officially have no clue why there were issues in the first place. Computers are fun -_-

**Comment by Scrumplex** [comment]
I think this was fixed in decky-loader. Closing this!
