### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by VRArt1** [libvibrant/vibrantDeck#4]
I might be wrong but I tried installing vibrantdeck through deckyloader and it didn't appear to be working. I tried moving the slider from 0 to max and disabling/enabling the games-only option and it didn't appear to make a difference in or out of games. I'm not sure if the version on decky loader is broken or if something broke with the latest steamos.

**Comment by Scrumplex** [comment]
Hmm weird. Are you running it on a Steam Deck?

**Comment by VRArt1** [comment]
That I am. I wasn't even aware decky loader was on other systems.

**Comment by Scrumplex** [comment]
> That I am. I wasn't even aware decky loader was on other systems.

There are community [efforts to make SteamOS 3 available for any system](https://github.com/theVakhovskeIsTaken/holoiso), so that's why I asked :D

I don't really know how to diagnose this issue on your end

**Comment by VRArt1** [comment]
Alright I seem to have fixed it. I decided I'd try resetting the console to see if that fixed it and it did indeed. I'm not sure if that's how you're supposed to use it or if it was supposed to automatically be working when you first install it or not.

**Comment by jctace** [comment]
Yes I also needed to restart the system after installing in order for changes to actually apply when using the slider.

**Comment by Scrumplex** [comment]
Closing this as resolved!
