### ISSUE TITLE
VibrantDeck settings are applied even if "Enable color settings" is disabled

### ISSUE THREAD

**Issue by Genadiii** [libvibrant/vibrantDeck#46]
Steps how I reproduce this issue:
1. Disable "Enable color settings" in the VibrantDeck settings.
2. Start a game
Then the gamma settings and saturation are reapllied.
If I then open the settings, then the toggle "Enable color settings" automatically switches from on to off and the VibratDeck settings will be disabled.
When I exit the game, the settings are applied again.

**Comment by Scrumplex** [comment]
Can confirm. Working on it!

**Comment by Scrumplex** [comment]
Fixed with commit e2b78ae4d8b8c8053058106442a6699c8fe50dfa
