### ISSUE TITLE
Color Saturation at 0

### ISSUE THREAD

**Issue by swoozi** [libvibrant/vibrantDeck#5]
Setting the color saturation 0 doesn't make it greyscale, instead, it adds more color. Likely back to default, 100.

**Comment by Scrumplex** [comment]
Can confirm. Probably a bug introduced with the recent update adding per-app overrides

**Comment by Scrumplex** [comment]
Fixed in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/46
