### ISSUE TITLE
Support gamescope 3.12.0 and SteamOS 3.5

### ISSUE THREAD

**Issue by Scrumplex** [libvibrant/vibrantDeck#62]
gamescope 3.12.0 will break vibrantDeck as the properties we have been using so far will be gone.

See https://github.com/ValveSoftware/gamescope/commit/dc60eba2463faa433bd906e78afea95dcfd176b4

We need to generate 3D LUTs instead.

**Comment by Scrumplex** [comment]
I got a work-in-progress version at https://github.com/libvibrant/vibrantDeck/pull/87

It doesn't have gamma options and the vibrancy slider only supports the "Color Vibrance" values in SteamOS' color settings (see screenshot below)

![SteamOS color settings](https://github.com/libvibrant/vibrantDeck/assets/11587657/90c315ec-19f2-4b80-af1c-a22adf235feb)

So for now it's a much less powerful version of the previous vibrantDeck.

It might be possible to increase the range of boosted colors to vibrantDeck 1.x levels by contributing some changes to Valve's gamescope directly. But that would take weeks to months to land in SteamOS anyway

**Comment by FlufflessMC** [comment]
Would be awesome

**Comment by Hedomec** [comment]
must have
