### ISSUE TITLE
Allow support for 3.5

### ISSUE THREAD

**Issue by Tintin-Asterix** [libvibrant/vibrantDeck#81]
The built in "sRGB" setting Valve added in 3.5 actually changes white to have a slight green cast _irrespective_ of the temperature slider. Really annoying, and there's no way around it. In their ultimate wisdom they decided to have some kind of preset that changes more than just the vibrancy/saturation with no way to _just_ boost vibrancy.

VibrantDeck doesn't have this issue. It lets you increase the colour values without adjusting tint. I wish it worked for 3.5.

I will just have to stay on 3.4 forever and never update my Steam Deck. :(

**Comment by xiibo** [comment]
Mine was slightly green until I enabled "Use Native Color Temperature" in the Display settings.

**Comment by Scrumplex** [comment]
This problem is tracked in #62
