### ISSUE TITLE
Steam OS 3.5.5 seems to have broken support for VibrantDeck

### ISSUE THREAD

**Issue by DNXPeeJay** [libvibrant/vibrantDeck#82]
Updated to 3.5.5 and noticed no changes when using VibrantDeck on or off. I love that Valve implemented their own display adjustment settings with this update but I feel as if I can’t capture the same vibrance in colors I got with VibrantDeck. It’s possible the difference really is negligible and it’s in my head but I would at least like to confirm with the settings on and off which I like more.

**Comment by Scrumplex** [comment]
This problem is tracked in #62
