### ISSUE TITLE
No longer working after update to 3.5.19

### ISSUE THREAD

**Issue by zeia0819** [libvibrant/vibrantDeck#93]
It gets me an error about SteamUI

**Comment by ImASadBoy** [comment]
+1

**Comment by Scrumplex** [comment]
An update has been merged quite some time ago here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/597

I am not sure when it will actually be rolled out to everyone.

**Comment by Scrumplex** [comment]
Seems like this will be fixed in a moment. I am closing this. Make sure to update to 2.0.1
